;;; haskell-tng-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from haskell-tng-compile.el

(register-definition-prefixes "haskell-tng-compile" '("haskell-tng-"))


;;; Generated autoloads from haskell-tng-contrib.el

(autoload 'haskell-tng-stylish-haskell "haskell-tng-contrib" "\
Apply `stylish-haskell' rules." t)
(autoload 'haskell-tng-stack2cabal "haskell-tng-contrib" "\
Prepare a stack project for use with cabal." t)
(autoload 'haskell-tng-goto-imports "haskell-tng-contrib" "\
Hack to jump to imports" t)
(autoload 'haskell-tng-current-module "haskell-tng-contrib" "\
Puts the current module name into the kill ring." t)
(autoload 'haskell-tng-filename-to-modulename "haskell-tng-contrib" "\
Infers the ModuleName for the current file based on filesystem layout.")


;;; Generated autoloads from haskell-tng-contrib-company.el

(register-definition-prefixes "haskell-tng-contrib-company" '("haskell-tng-"))


;;; Generated autoloads from haskell-tng-contrib-smartparens.el

(register-definition-prefixes "haskell-tng-contrib-smartparens" '("haskell-tng--contrib-sp-indent"))


;;; Generated autoloads from haskell-tng-font-lock.el

(register-definition-prefixes "haskell-tng-font-lock" '("haskell-tng--font-lock-"))


;;; Generated autoloads from haskell-tng-hsinspect.el

(put 'haskell-tng-hsinspect-langexts 'safe-local-variable #'listp)
(autoload 'haskell-tng-fqn-at-point "haskell-tng-hsinspect" "\
Consult the imports in scope and display the fully qualified
name of the symbol at point in the minibuffer." t)
(register-definition-prefixes "haskell-tng-hsinspect" '("haskell-tng-"))


;;; Generated autoloads from haskell-tng-imenu.el

(register-definition-prefixes "haskell-tng-imenu" '("haskell-tng--imenu-create"))


;;; Generated autoloads from haskell-tng-layout.el

(register-definition-prefixes "haskell-tng-layout" '("haskell-tng--layout-"))


;;; Generated autoloads from haskell-tng-lexer.el

(register-definition-prefixes "haskell-tng-lexer" '("haskell-tng--lexer-"))


;;; Generated autoloads from haskell-tng-mode.el

(autoload 'haskell-tng-mode "haskell-tng-mode" "\
Major mode for editing Haskell programs.

(fn)" t)
(add-to-list 'auto-mode-alist `(,(rx ".hs" eos) . haskell-tng-mode))
(modify-coding-system-alist 'file (rx ".hs" eos) 'utf-8)
(register-definition-prefixes "haskell-tng-mode" '("haskell-tng-prettify-symbols"))


;;; Generated autoloads from haskell-tng-rx.el

(register-definition-prefixes "haskell-tng-rx" '("haskell-tng--"))


;;; Generated autoloads from haskell-tng-smie.el

(register-definition-prefixes "haskell-tng-smie" '("haskell-tng-"))


;;; Generated autoloads from haskell-tng-syntax.el

(register-definition-prefixes "haskell-tng-syntax" '("haskell-tng--syntax-"))


;;; Generated autoloads from haskell-tng-util.el

(register-definition-prefixes "haskell-tng-util" '("haskell-tng--util-"))

;;; End of scraped data

(provide 'haskell-tng-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; haskell-tng-mode-autoloads.el ends here
